// =============================================================
// PENJELASAN FILE: lib/firebase_options.dart
// File ini sudah diberi komentar singkat agar mudah dipresentasikan.
// Komentar tidak mengubah fungsi kode, hanya menjelaskan kegunaannya.
// =============================================================

// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
// Import package/file yang dibutuhkan oleh halaman ini.
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// Import package/file yang dibutuhkan oleh halaman ini.
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
// Class DefaultFirebaseOptions menyimpan struktur atau logic utama.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    // Percabangan untuk mengecek kondisi tertentu.
    if (kIsWeb) {
      // Mengembalikan hasil dari function/widget.
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        // Mengembalikan hasil dari function/widget.
        return android;
      case TargetPlatform.iOS:
        // Mengembalikan hasil dari function/widget.
        return ios;
      case TargetPlatform.macOS:
        // Mengembalikan hasil dari function/widget.
        return macos;
      case TargetPlatform.windows:
        // Mengembalikan hasil dari function/widget.
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQrlFRr8QYruulxZfdrWVdchsbMHQ1rLM',
    appId: '1:350426373336:web:92a344629752813c254bad',
    messagingSenderId: '350426373336',
    projectId: 'borneo-scholar',
    authDomain: 'borneo-scholar.firebaseapp.com',
    storageBucket: 'borneo-scholar.firebasestorage.app',
    measurementId: 'G-1P045LGZ9W',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDYdnppwh44KuP8yk1MrS_JWTQWPFTPyVw',
    appId: '1:350426373336:android:5a3381d9a25252a6254bad',
    messagingSenderId: '350426373336',
    projectId: 'borneo-scholar',
    storageBucket: 'borneo-scholar.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVh3ZZu98k5gKvnVWyF47gseu1WpULLPA',
    appId: '1:350426373336:ios:686aec7d2ec267b7254bad',
    messagingSenderId: '350426373336',
    projectId: 'borneo-scholar',
    storageBucket: 'borneo-scholar.firebasestorage.app',
    iosBundleId: 'com.example.borneoScholar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVh3ZZu98k5gKvnVWyF47gseu1WpULLPA',
    appId: '1:350426373336:ios:686aec7d2ec267b7254bad',
    messagingSenderId: '350426373336',
    projectId: 'borneo-scholar',
    storageBucket: 'borneo-scholar.firebasestorage.app',
    iosBundleId: 'com.example.borneoScholar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBQrlFRr8QYruulxZfdrWVdchsbMHQ1rLM',
    appId: '1:350426373336:web:9b973abe54cb7086254bad',
    messagingSenderId: '350426373336',
    projectId: 'borneo-scholar',
    authDomain: 'borneo-scholar.firebaseapp.com',
    storageBucket: 'borneo-scholar.firebasestorage.app',
    measurementId: 'G-C69R9GW54G',
  );

}
